name: Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
      
    steps:
    
      - name: Install latest git
        run: pacman -Syy --noconfirm git

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
          pacman -Syyu --noconfirm && pacman -S --noconfirm base-devel archiso

      - name: Build packages
        run: |
          sudo mkarchiso -v .