name: Build

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: pacman -Syyu --noconfirm && pacman -S --noconfirm base-devel archiso

      - name: Build iso file
        run: sudo mkarchiso -v .

      - name: Rename file
        run: mv out/*.iso out/arch-live-disk-mgr.iso

      - name: Upload to s3
        uses: yakubique/minio-upload@v1.1.3
        with:
          endpoint: ${{ secrets.AWS_ENDPOINT }}
          access_key: ${{ secrets.AWS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.AWS_BUCKET }}
          source: ./out/arch-live-disk-mgr.iso
          target: '/'
          # Disables TLS/SSL certificate verification. Allows TLS connectivity to servers with invalid certificates.
          insecure: true
